version: "3"
services:
  web_prod:
    image: "registry.gitlab.com/ort.lyon.enseignement.numerique/3olen/2023.2024-lumos-camminus/projet-31/1001-librairies/bibliolen-dev:1.0.0"
    container_name: "bibliolen-prod"
    restart: unless-stopped
    volumes:
      - "/home/librairies/Documents/docker_volumes/bibliolen_images_prod:/var/www/html/public/img/couvertures"
    networks:
      N_Prod:
        ipv4_address: 192.168.0.11
    environment:
      - "APP_NAME=BibliOlen"
      - "DB_HOST=192.168.0.12"
      - "DB_PORT=5432"
      - "DB_NAME=projet31"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=CHANGE_ME"
  db_prod:
    image: "postgres:16.1"
    container_name: "bibliolen-db-prod"
    volumes:
      - "/home/librairies/Documents/docker_volumes/bibliolen_db_prod:/var/lib/postgresql/data"
    networks:
      N_Prod:
        ipv4_address: 192.168.0.12
    environment:
      POSTGRES_PASSWORD: CHANGE_ME

networks:
  N_Prod:
    external: true
