version: "3"
services:
  web:
    build: .
    container_name: "bibliolen-dev"
    ports:
      - "8080:8080"
    environment:
      - "APP_NAME=BibliOlen"
      - "DB_HOST=172.29.0.4"
      - "DB_PORT=5432"
      - "DB_NAME=projet31"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=CHANGE_ME"
  db:
    image: postgres
    container_name: "bibliolen-db-dev"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: CHANGE_ME
