INSERT INTO mots_cles (mot_cle)
VALUES ('Recette'),
       ('Benchmarking'),
       ('Microsoft Azure'),
       ('SQL'),
       ('Microsoft MVP'),
       ('PowerShell'),
       ('Transformation numérique'),
       ('Gestion des risques'),
       ('Base de données décisionnelle'),
       ('Java'),
       ('Bash'),
       ('Prometheus'),
       ('User Story'),
       ('Gestion de projet web'),
       ('CI/CD'),
       ('Chiffrage'),
       ('PRINCE2'),
       ('Maven'),
       ('Projet web'),
       ('Scripting'),
       ('UML'),
       ('DevOps'),
       ('Programmation logicielle'),
       ('Microsoft'),
       ('Réseaux'),
       ('Framework'),
       ('MVC'),
       ('Symfony'),
       ('Shell'),
       ('Swarm'),
       ('Infrastructure'),
       ('Administration de serveur'),
       ('SCRUM'),
       ('Business Intelligence'),
       ('Kubernetes'),
       ('Reverse engineering'),
       ('Conduite de projet'),
       ('Linux'),
       ('JavaScript'),
       ('Design Patterns'),
       ('OLAP'),
       ('Scrum'),
       ('Python'),
       ('Monitoring'),
       ('Modélisation'),
       ('Java EE'),
       ('Profiling'),
       ('GNU'),
       ('Application mobile'),
       ('Ethical hacking'),
       ('Malwares'),
       ('Stockage'),
       ('PHP'),
       ('Application Symfony'),
       ('Hyper-V'),
       ('Administration système'),
       ('Méthode agile'),
       ('OpenStack'),
       ('Cybersécurité'),
       ('Jakarta EE'),
       ('Administration réseau'),
       ('Application JavaScript'),
       ('Application Python'),
       ('Spring'),
       ('Firewall'),
       ('Gestion de projet'),
       ('Pilotage'),
       ('Docker'),
       ('Règlementations'),
       ('AWS'),
       ('Application React'),
       ('Résilience'),
       ('Red Hat'),
       ('Développement web'),
       ('Rocky Linux'),
       ('Windows 11'),
       ('IA'),
       ('Cloud'),
       ('PostgreSQL'),
       ('Visual Studio'),
       ('CentOS'),
       ('Orchestration'),
       ('Performance'),
       ('Windows'),
       ('Système d''exploitation'),
       ('RGPD'),
       ('Diagramme de PERT'),
       ('Supervision'),
       ('.NET'),
       ('Développement'),
       ('Application Java'),
       ('Programmation système'),
       ('Grafana'),
       ('Business analyst'),
       ('Bonnes pratiques'),
       ('SecOps'),
       ('TCP/IP'),
       ('Kanban'),
       ('Windows Server'),
       ('Application C#'),
       ('C#'),
       ('Diagramme de GANTT'),
       ('Planning'),
       ('React'),
       ('Application JEE'),
       ('Amazon Web Services'),
       ('Sécurité'),
       ('Intelligence Artificielle'),
       ('Application web'),
       ('SGBDR'),
       ('Application .NET'),
       ('Automatisation'),
       ('Projet agile'),
       ('Web'),
       ('Planification'),
       ('BI'),
       ('Conteneur'),
       ('DevSecOps'),
       ('Base de données'),
       ('Conception')
ON CONFLICT (mot_cle) DO NOTHING;

INSERT INTO auteurs (nom_auteur, prenom_auteur)
SELECT nom_auteur, prenom_auteur
FROM (VALUES ('CLARHAUT', 'Joffrey'),
             ('VICOGNE', 'Frédéric'),
             ('HUGON', 'Jérôme'),
             ('BEZET-TORRES', 'Jérôme'),
             ('DAUSSIN', 'David'),
             ('LE MORVAN', 'Hervé'),
             ('Bonnet', 'Christophe'),
             ('BADREAU', 'Stéphane'),
             ('CHAZALLET', 'Sébastien'),
             ('BISSON', 'Anne-Christine'),
             ('ACISSI', 'Association'),
             ('DUBOURGNOUX', 'Rémi'),
             ('HAAS', 'Gérard'),
             ('SCHALKWIJK', 'Laurent'),
             ('Israel', 'Marc'),
             ('BONNET', 'Nicolas'),
             ('VOLANT', 'Loïc'),
             ('EBEL', 'Franck'),
             ('Bourcy', 'Thierry'),
             ('BEIRNAERT-HUVELLE', 'Jacques'),
             ('Ebel', 'Franck'),
             ('HENNECART', 'Jérôme'),
             ('LARDIÈRE', 'Sébastien'),
             ('RASCAGNERES', 'Paul'),
             ('ANDRIANOELISON', 'Hajasolo'),
             ('LANGLET', 'Étienne'),
             ('CROCFER', 'Robert'),
             ('LADENT', 'Étienne'),
             ('BRILLANT', 'Alexandre'),
             ('PONS', 'Nicolas'),
             ('PERRÉ', 'Yannig'),
             ('LANGLET', 'Etienne'),
             ('ASTIER', 'Stéphane'),
             ('RODRIGUEZ', 'Jean-Michel'),
             ('MOMMER', 'Christophe'),
             ('LE MASNE', 'Thibaut'),
             ('CABANTOUS', 'Pierre'),
             ('DEBRAUWER', 'Laurent'),
             ('LARINIER', 'Sébastien'),
             ('VAN ROBAEYS', 'Damien'),
             ('BARTOLONE', 'Thibault'),
             ('RAULT', 'Raphaël'),
             ('GUÉRIN', 'Brice-Arnaud'),
             ('LASSON', 'Sébastien'),
             ('DUMINIL', 'Nicolas'),
             ('GOUIGOUX', 'Jean-Philippe'),
             ('FORTUNATO', 'Guillaume'),
             ('Sébastien', 'Déon'),
             ('ASSOULINE', 'Jordan'),
             ('HIARD', 'Vincent'),
             ('BANCAL', 'Damien'),
             ('GRÉAU', 'Maxime'),
             ('SÉBASTIEN', 'Castiel'),
             ('POLINI', 'Eva'),
             ('NORIE', 'Eric')) AS data(nom_auteur, prenom_auteur)
WHERE NOT EXISTS (SELECT 1
                  FROM auteurs
                  WHERE auteurs.nom_auteur = data.nom_auteur
                    AND auteurs.prenom_auteur = data.prenom_auteur);


INSERT INTO editeurs (nom_editeur)
VALUES ('Éditions ENI')
ON CONFLICT (nom_editeur) DO NOTHING;

INSERT INTO livres (titre_livre, resume_livre, isbn, annee_publication, image_couverture, nombre_exemplaires,
                    id_editeur)
SELECT titre_livre,
       resume_livre,
       isbn,
       annee_publication,
       image_couverture,
       nombre_exemplaires,
       id_editeur
FROM (VALUES ('Windows Server 2022 - Les bases indispensables pour administrer et configurer votre serveur',
              'Ce livre sur Windows Server 2022 s''adresse à tout administrateur ou futur administrateur de serveurs Windows. Il a pour objectif de vous donner les bases indispensables pour administrer et configurer votre serveur.',
              '9782409037641', 2022, '9782409037641.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Symfony 5 - Développez des sites web PHP structurés et performants',
              'Ce livre sur Symfony 5 s''adresse aux développeurs, chefs de projet, architectes techniques, qui souhaitent, grâce à ce framework, structurer et organiser leurs développements PHP au sein d''un environnement de construction d''applications robuste et professionnel. La maîtrise de la programmation objet avec PHP est un prérequis indispensable pour tirer le meilleur parti de ces pages.',
              '9782409037221', 2022, '9782409037221.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Apache Maven - Maîtrisez l''infrastructure d''un projet Java EE',
              'Ce livre sur Apache Maven (en version 3.6 au moment de l''écriture) s''adresse à tout développeur amené à travailler sur des projets Java de taille conséquente. Il sert également de guide pour les architectes qui souhaitent mettre en œuvre Apache Maven sur un nouveau projet ou sur un projet existant.',
              '9782409019531', 2019, '9782409019531.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('AWS : Gérez votre infrastructure sur la plateforme cloud d''Amazon',
              'Cet ouvrage propose un voyage au coeur de la plateforme cloud Amazon Web Services et de ses services lors duquel le lecteur trouvera toutes les informations nécessaires sur la conception, le développement et l''administration d''une infrastructure AWS. Il s''adresse à toute personne qui souhaite explorer les subtilités du cloud computing et des principaux services d''AWS pour faire tourner ses applications.',
              '9782409022180', 2019, '9782409022180.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('C# 10 - Développez des applications Windows avec Visual Studio 2022',
              'Ce livre sur le développement d''applications Windows avec le langage C# (en version 10) et Visual Studio 2022 est destiné aux développeurs qui débutent avec le framework .NET. Il leur permet d''apprendre les bases du langage C# et introduit des concepts plus avancés leur donnant une vue d''ensemble des possibilités offertes par le langage C#, Visual Studio et le framework .NET en général. L''auteur a choisi une approche pas à pas tout en construisant une application fonctionnelle tout au long de l''ouvrage pour illustrer de manière pratique et cohérente les concepts abordés.',
              '9782409035135', 2022, '9782409035135.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Conduite de projets informatiques - Développement, analyse et pilotage',
              'Ce livre sur la conduite de projets informatiques s’adresse à un public d’informaticiens, de chefs de projet, qu’ils soient professionnels ou étudiants. Il présente la conduite de projets d’une façon concrète et abordable, en fournissant les éléments clés d’un projet réussi : analyse, suivi, bilan.',
              '9782409037368', 2022, '9782409037368.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Docker - Concepts fondamentaux et déploiement d''applications conçues en services',
              'Ce livre s’adresse aux développeurs, architectes et administrateurs système, ainsi qu’à toute personne désireuse de comprendre les concepts fondamentaux de la technologie Docker, sans entrer dans toutes ses subtilités ni tous ses cas d’usage, pour les mettre en œuvre dans le déploiement d’applications conçues en services.',
              '9782409038068', 2022, '9782409038068.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Cybersécurité et PowerShell: De l''attaque à la défense du système d''information',
              'Ce livre traite de la sécurité des systèmes d’information à travers le prisme du langage PowerShell. Il s’adresse aux administrateurs système et réseau, experts ou consultants en cybersécurité, chefs de projet ou responsables cyber qui souhaitent comprendre le rôle et les capacités du langage de scripting de Microsoft dans le domaine de la cybersécurité.',
              '9782409034145', 2022, '9782409034145.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Design Patterns en Java - Descriptions et solutions illustrées en UML 2 et Java - Les 23 modèles de conception',
              'Ce livre présente de façon concise et pratique les 23 modèles de conception (design patterns) fondamentaux en les illustrant par des exemples pertinents et rapides à appréhender. Chaque exemple est décrit en UML et en Java sous la forme d''un petit programme complet et exécutable. Pour chaque pattern, l''auteur détaille son nom, le problème correspondant, la solution apportée, ses domaines d''application et sa structure générique.',
              '9782409037603', 2022, '9782409037603.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Débuter avec PowerShell',
              'Le langage de scripting PowerShell permettant l’automatisation d’un certain nombre de tâches facilite le quotidien des informaticiens. Que vous soyez étudiants, techniciens, administrateurs système, ingénieurs ou que vous souhaitiez simplement découvrir ce qu’est PowerShell, ce livre vous permettra d’apprendre les bases du langage en partant de zéro et de découvrir l’étendue de ses possibilités.',
              '9782409039645', 2023, '9782409039645.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Écrire du code .NET performant - Profilage, benchmarking et bonnes pratiques',
              'Ce livre sur la performance du code .NET s’adresse aux développeurs débutants comme expérimentés qui ont à faire face à des problèmes de performances sur leurs développements.',
              '9782409036132', 2022, '9782409036132.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Gestion d''un projet web - Planification, pilotage et bonnes pratiques',
              'Ce livre sur la gestion d''un projet web s''adresse à tout public tant son approche fonctionnelle en facilite la prise en main. Il apporte une méthodologie de conduite de projet, basée sur l''expérience de l''auteur, qui passe en revue toutes les étapes fondamentales du cycle de vie d''un projet web.',
              '9782409019128', 2019, '9782409019128.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Gestion de projet agile - De la définition du besoin à la livraison d''un produit de qualité',
              'Cet ouvrage est destiné à toute personne impliquée dans un projet agile et s’adresse particulièrement aux responsables de produit et aux analystes qui sont au contact avec les utilisateurs et en charge de la définition d’un produit. Ils trouveront dans ce livre les informations utiles pour maîtriser les techniques fondamentales pour recueillir le besoin et le formuler correctement.',
              '9782409033391', 2021, '9782409033391.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Java Spring - Le socle technique des applications Jakarta EE',
              'Ce livre apporte les éléments clés pour se repérer dans les différentes technologies utilisées dans les projets basés sur Spring. Il prend en compte les différences de configuration liées aux versions de Spring (en version 4.3 et 5.3 au moment de l’écriture) et se base sur des exemples concrets d’utilisation. Il permet au lecteur d’être très rapidement autonome sur un projet d’entreprise qui utilise Spring, que ce soit au début d’un nouveau projet ou pour maintenir un projet existant : compréhension du noyau, accès aux données, maîtrise de la couche web. Des connaissances sur le développement Java et notamment le développement d’applications web sont un prérequis indispensable pour tirer le meilleur parti possible du livre.',
              '9782409036552', 2022, '9782409036552.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('JavaScript - Développez efficacement',
              'Ce livre sur JavaScript s''adresse à des développeurs soucieux de progresser dans leurs compétences JavaScript et de passer de la maîtrise syntaxique à la maîtrise du cycle de développement complet. Une première expérience du développement avec JavaScript, dans sa syntaxe de base, est indispensable à la bonne compréhension de cet ouvrage.',
              '9782409038341', 2023, '9782409038341.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('La sécurité sous Windows 11 - Renforcez votre système d''exploitation',
              'Ce livre s’adresse aux responsables des systèmes d’information des entreprises ainsi qu’à toute personne désireuse d’optimiser la sécurité de son système d’exploitation. Il apporte les connaissances nécessaires à la compréhension et à la maîtrise de la sécurité sous Windows 11.',
              '9782409037429', 2022, '9782409037429.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Le cloud privé avec OpenStack - Guide pratique pour l''architecture, l''administration et l''implémentation',
              'Cet ouvrage sur OpenStack, plateforme open source permettant de créer et gérer des infrastructures cloud, a pour objectif d’outiller le lecteur pour le rendre autonome dans son utilisation quotidienne ou pour une implémentation en entreprise. Il se propose de démythifier OpenStack avec une approche par la pratique grâce au retour d’expérience de l’auteur.',
              '9782409038693', 2023, '9782409038693.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Le réseau avec microsoft azure - déployez, hybridez et sécurisez vos réseaux dans le cloud',
              'Avec l’avènement des technologies cloud, les réseaux d’entreprises doivent inévitablement faire face à de nouveaux enjeux d’hybridation, de sécurisation et d’optimisation. Ce livre s’adresse à toute personne (expert technique, architecte, consultant, ingénieur réseau...) qui souhaite appréhender techniquement l’ensemble des services réseau proposés dans le cloud Azure en considérant à la fois le coût et les enjeux de sécurité dans le choix d’une architecture.',
              '9782409034121', 2022, '9782409034121.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Les réseaux informatiques - Guide pratique pour l''administration, la sécurité et la supervision',
              'Ce livre sur les réseaux informatiques s''adresse aussi bien aux administrateurs réseau, techniciens ou ingénieurs en charge de la conception, de l''administration, de la sécurité et de la mise en place de solutions de supervision d''un réseau, qu''aux étudiants souhaitant disposer de connaissances théoriques et techniques nécessaires pour exercer le métier d''administrateur réseau au sens large.',
              '9782409038389', 2023, '9782409038389.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Linux - Principes de base de l''utilisation du système',
              'Ce livre sur GNU/Linux s''adresse à tout informaticien désireux de maîtriser les principes de base de ce système d''exploitation ou d''organiser et consolider des connaissances acquises sur le terrain.',
              '9782409037764', 2022, '9782409037764.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('PostgreSQL',
              'L''utilisateur de bases de données trouvera dans ce livre les informations indispensables pour exploiter au mieux les possibilités de PostgreSQL (en version 12 au moment de la rédaction).',
              '9782409024504', 2020, '9782409024504.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('PRINCE2® - Une méthode pour maîtriser la gestion de vos projets',
              'Ce livre sur PRINCE2® propose aux lecteurs d''acquérir une bonne compréhension de la méthodologie PRINCE2® dans sa 6e édition. Il leur permettra de découvrir l''intérêt d''une méthode de gestion de projet structurée et de comprendre les avantages d''une approche processus pour assurer le contrôle d''un projet.',
              '9782409038327', 2023, '9782409038327.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Prometheus et Grafana - Surveillez vos applications et composants système',
              'Avec ce livre, illustré par de nombreux exemples de mise en œuvre, les administrateurs système comme les développeurs apprendront à déployer l’outil de surveillance Prometheus, interfacé avec l’outil de visualisation de données Grafana, pour mieux maîtriser la surveillance de leurs applications ou de leurs composants système.',
              '9782409031748', 2021, '9782409031748.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Red Hat Enterprise Linux - CentOS - Mise en production et administration de serveurs: Mise en production et administration de serveurs',
              'Ce livre sur Red Hat Enterprise Linux et CentOS, ainsi que Rocky Linux (versions 8 et 9) s''adresse à tout informaticien appelé à déployer un serveur Linux performant en entreprise et à en assurer l''administration. Émaillé d''explications pédagogiques, d''exemples et d''astuces, ce livre va à l''essentiel, fournit des méthodes techniques et logistiques, présente les bonnes pratiques et n''oublie pas la sécurité.',
              '9782409037726', 2022, '9782409037726.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Python 3 - Les fondamentaux du langage',
              'Ce livre sur les fondamentaux du langage Python 3 (en version 3.8 beta au moment de l''écriture) s''adresse à tout professionnel de l''informatique, ingénieur, étudiant (et particulièrement en BTS Services Informatiques Organisations), enseignant ou même autodidacte qui souhaite maîtriser ce langage très abouti. Il couvre un périmètre relativement large, détaille tout le coeur du langage et du traitement de données et ouvre des perspectives importantes sur tout ce que Python 3 permet de faire (de la création d''un site web au développement de jeux en passant par la conception d''une interface graphique avec Gtk).',
              '9782409020964', 2019, '9782409020964.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('React',
              'Ce livre s''adresse aux développeurs qui souhaitent lever la complexité apparente du framework Front End React pour réaliser des applications web et mobiles bien architecturées et aisées à maintenir. Pour bien appréhender la lecture de ce livre, un minimum de connaissances sur le langage JavaScript, et en particulier sur les nouveautés apportées par ES2015, est un plus.',
              '9782409022722', 2020, '9782409022722.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Scripting Python sous Linux - Développez vos outils système',
              'Ce livre s''adresse aux ingénieurs système qui souhaitent écrire leurs propres outils d''administration d''un système Linux à l''aide du langage Python. Articulé en trois parties, ce livre donne les explications nécessaires au lecteur, suivies d''exemples concrets de difficulté croissante, pour ainsi étendre les possibilités du shell. La connaissance d''un autre langage de programmation, d''un système Linux (quelle que soit la distribution) et des principes de base d''Unix est un plus pour la lecture de ce livre.',
              '9782409025679', 2020, '9782409025679.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('SQL - Les fondamentaux du langage (avec exercices et corrigés)',
              'Ce livre sur les fondamentaux du langage SQL s''adresse aux développeurs et informaticiens débutants appelés à travailler avec un Système de Gestion de Bases de Données Relationnelles (SGBDR) pour stocker et manipuler des données. Son objectif est de décrire les ordres principaux les plus utilisés du langage SQL (indépendamment des déclinaisons réalisées par les éditeurs de SGBDR) pour permettre au lecteur de prendre en main rapidement une base de données relationnelle et être capable de créer des tables, de les interroger, de les modifier, d''insérer et de supprimer des lignes.',
              '9782409026553', 2020, '9782409026553.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Intelligence Artificielle - Impact sur les entreprises et le business',
              'L''Intelligence Artificielle ou IA est au coeur de nombreux débats et est le fer de lance de beaucoup d’entreprises. Il ne se passe plus une journée sans qu''une communication ne soit faite sur une nouvelle intelligence artificielle capable d''en faire plus que la précédente. La guerre industrielle est lancée et on peut facilement imaginer qu''elle ne se terminera que par une entité artificielle égale ou supérieure à l''humain. C''est dans ce nouveau monde qui se prépare qu''apparaît la branche cognitive de l''intelligence artificielle qui s''appuie sur des domaines et outils tels que l''apprentissage et l''auto-apprentissage, les réseaux de neurones, la langue naturelle, les arbres de décision dont les objectifs sont de déduire des faits marquants, repérer des motifs, prédire des tendances, imaginer de nouveaux services à mettre en place et ainsi aider l''humain à décider. Mais cela ne se fait pas sans inquiétudes, tout d''abord les biais qui peuvent fausser les interprétations et donc les décisions et ensuite l''impact que l''intelligence artificielle va avoir sur nos activités, nos rôles et nos métiers.',
              '9782409038006', 2022, '9782409038006.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('La transformation digitale des entreprises - Plongez de l''autre côté du miroir',
              'La transformation digitale des entreprises, terme popularisé dans les années 2016, reste, encore aujourd''hui, un sujet d’actualité empreint de nombreuses attentes qui ont du mal à porter leurs fruits. Les raisons sont nombreuses : une mauvaise compréhension du sujet, une problématique d’organisation, une erreur dans les objectifs fixés etc.',
              '9782409031953', 2021, '9782409031953.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Cloud privé, hybride et public - Quel modèle pour quelle utilisation ? Un état de l''art et des bonnes pratiques',
              'Le cloud est très souvent utilisé sans vraiment que l''on s''en rende compte. Cependant, il n''est ni la panacée à tous les défis des entreprises, ni le démon qui ouvre la porte à tous les risques sécuritaires. Dans ce livre qui s''adresse aux dirigeants ou aux directeurs des systèmes d''information, l''auteur apporte un éclairage teinté d''expérience sur les questions et les réponses à apporter pour utiliser le cloud avec succès.',
              '9782409012426', 2018, '9782409012426.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Intelligence artificielle - Enjeux éthiques et juridiques',
              'Après l''avènement de la société de l''information et la digitalisation de pans entiers d''activités de notre société, la révolution de l''IA est en marche. Cette (r)évolution s''accompagne d''une médiatisation tous azimuts, oscillant entre fantasmes dystopiques et électrochocs nécessaires d''une opinion publique souvent perdue au sein de ce maelström. Une chose est sûre, l''IA occupe les pensées et vient bouleverser notre droit.',
              '9782409031342', 2021, '9782409031342.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Business Intelligence : le recueil des besoins - La boîte à outils du business analyst',
              'Un processus de recueil des besoins correctement mené est la garantie de succès de votre projet décisionnel. Il est donc capital pour le business analyst, le chef de projet, le développeur et les parties prenantes fonctionnelles de choisir la bonne approche et d''aller au-delà de la simple interview ou de l''inévitable workshop. Au-delà de faciliter la communication et la mutuelle compréhension des différents acteurs, le but de ce livre est de donner des outils permettant d''élargir les pratiques du recueil des besoins.',
              '9782409024986', 2020, '9782409024986.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Modélisation décisionnelle - Concevoir la base de données pour les traitements OLAP',
              'Ce livre a pour objectif de fournir au lecteur toutes les clés pour concevoir une base de données décisionnelle efficace, s''intégrant parfaitement à une solution OLAP et permettant également d''entrevoir des nouvelles possibilités dans la manipulation de la donnée. Il s''adresse à un public ayant déjà des connaissances en bases de données. La connaissance des progiciels décisionnels est un plus mais n''est pas indispensable.',
              '9782409007934', 2017, '9782409007934.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Cyber résilience en entreprise : enjeux, référentiels et bonnes pratiques',
              'Ce livre sur la cyber résilience en entreprise est destiné aux personnes en charge de mettre en oeuvre la sécurité informatique au sein des entreprises (DSI, RSSI, Directeur Cybersécurité, experts et consultants...) qui souhaitent comprendre les enjeux et contraintes de la cybersécurité et qui souhaitent s''impliquer dans l''amélioration continue de la sécurité des Systèmes d''Information. Il est un véritable guide pour la mise en oeuvre de la cyber résilience des systèmes d''information reposant sur quatre dimensions : cyber-prévention, cyber-détection, cyber-protection et cyber-remédiation.',
              '9782409031380', 2021, '9782409031380.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Hacking et Forensic - Développez vos propres outils en Python',
              'Ce livre s''adresse à toute personne désirant apprendre le Python pour le Hacking et Forensic et se former à la conception d''outils en Python ainsi qu''aux professionnels de la sécurité informatique, du Forensic. Il a pour objectif de conduire le lecteur à une bonne compréhension de bibliothèques spécifiques Python pour qu''il puisse ensuite concevoir ses outils personnalisés, adaptés à des situations particulières en Hacking et Forensic.',
              '9782746099715', 2016, '9782746099715.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Cybersécurité et Malwares - Détection, analyse et Threat Intelligence',
              'Ce livre décrit les techniques et la méthodologie utilisées par les professionnels de l’analyse de malwares (ou logiciels malveillants). Il s’adresse à des informaticiens passionnés de sécurité, à des professionnels dans le domaine de la sécurité informatique, qui souhaitent une approche opérationnelle et hautement technique.',
              '9782409038105', 2022, '9782409038105.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('DevSecOps - Développez et administrez vos services en toute sécurité',
              'Cet ouvrage sur l''approche DevSecOps est destiné à tout membre d''une équipe opérationnelle IT ou de développement qui souhaite intégrer la sécurité dans sa pratique quotidienne et disposer des bons outils pour sécuriser ses développements, à chaque étape du cycle de vie des services. L''auteur commence par expliquer en quoi l''implémentation de la sécurité transforme en profondeur le fonctionnement des équipes au sein d''une entreprise, notamment les équipes de développement, avant de présenter en détail les notions d''intégration continue et de déploiement continu (CI/CD).',
              '9782409039188', 2023, '9782409039188.jpg', 2,
              (SELECT id_editeur FROM editeurs WHERE nom_editeur = 'Éditions ENI' LIMIT 1)),
             ('Sécurité informatique - Ethical Hacking, Apprendre l''attaque pour mieux se défendre',
              'Ce livre sur la sécurité informatique (et le ethical hacking) s''adresse à tout informaticien sensibilisé au concept de la sécurité informatique mais novice ou débutant dans le domaine de la sécurité des systèmes d''information. Il a pour objectif d''initier le lecteur aux techniques des attaquants pour lui apprendre comment se défendre. Cette nouvelle édition tient compte de l''actualité en matière de sécurité informatique et voit l''apparition de trois nouveaux chapitres qui traitent de la sécurité des mobiles, des voitures connectées et de l''étude des malwares.',
              '9782409033667', 2022, '9782409033667.jpg', 2,
              (SELECT id_editeur
               FROM editeurs
               WHERE nom_editeur = 'Éditions ENI'
               LIMIT 1)))
         AS data(titre_livre, resume_livre, isbn, annee_publication, image_couverture, nombre_exemplaires, id_editeur)
WHERE NOT EXISTS (SELECT 1 FROM livres WHERE isbn = data.isbn);

INSERT INTO livre_mots_cles (id_livre, id_mot_cle)
VALUES ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Infrastructure' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Microsoft' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows Server' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration de serveur' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Hyper-V' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PowerShell' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Microsoft MVP' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PHP' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Symfony' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Framework' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application Symfony' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Java' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Maven' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Java EE' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Automatisation' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application JEE' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cloud' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Amazon Web Services' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'AWS' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Infrastructure' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'DevOps' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Stockage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'C#' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Visual Studio' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application C#' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Programmation logicielle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Conduite de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Pilotage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Recette' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Chiffrage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Planning' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion des risques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SCRUM' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Kanban' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'RGPD' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Docker' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Conteneur' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Orchestration' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'DevOps' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Infrastructure' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Swarm' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Kubernetes' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034145'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034145'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PowerShell' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034145'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034145'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Java' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Design Patterns' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Conception' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application Java' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'UML' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Programmation logicielle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'MVC' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PowerShell' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Microsoft' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = '.NET' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Performance' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Benchmarking' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Profiling' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application .NET' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Programmation logicielle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Projet web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Pilotage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Planification' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Diagramme de GANTT' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Diagramme de PERT' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bonnes pratiques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scrum' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Kanban' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'User Story' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Méthode agile' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Pilotage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Recette' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Projet agile' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Planification' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Java' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Spring' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Jakarta EE' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application Java' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Framework' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038341'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'JavaScript' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038341'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038341'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038341'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application JavaScript' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Windows 11' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Microsoft' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cloud' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'OpenStack' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Infrastructure' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cloud' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Microsoft Azure' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration réseau' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Supervision' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'TCP/IP' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Firewall' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Linux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Système d''exploitation' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'GNU' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Shell' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bash' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024504'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PostgreSQL' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024504'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Base de données' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024504'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SQL' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024504'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SGBDR' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion de projet' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'PRINCE2' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Pilotage' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Planification' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Gestion des risques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Prometheus' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Grafana' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Supervision' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Monitoring' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Linux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Red Hat' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'CentOS' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Rocky Linux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Système d''exploitation' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bash' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Python' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application Python' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'React' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Développement' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application web' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application mobile' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Framework' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'JavaScript' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Application React' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409025679'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Python' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409025679'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Linux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409025679'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Administration système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409025679'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409026553'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SQL' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409026553'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Base de données' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409026553'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SGBDR' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038006'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'IA' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038006'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Intelligence Artificielle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038006'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Transformation numérique' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031953'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Transformation numérique' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409012426'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cloud' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409012426'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'RGPD' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409012426'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409012426'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bonnes pratiques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031342'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'IA' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031342'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Intelligence Artificielle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024986'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'BI' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024986'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Business Intelligence' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024986'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Business analyst' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'BI' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Business Intelligence' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'OLAP' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Base de données décisionnelle' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Conception' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Modélisation' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031380'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031380'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Règlementations' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031380'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bonnes pratiques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031380'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Résilience' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782746099715'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782746099715'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Python' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782746099715'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Scripting' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782746099715'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Réseaux' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038105'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038105'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Malwares' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038105'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Reverse engineering' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'DevSecOps' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'SecOps' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'DevOps' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'CI/CD' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Docker' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Kubernetes' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Bonnes pratiques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Cybersécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Sécurité' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Ethical hacking' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'Programmation système' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_mot_cle FROM mots_cles WHERE mot_cle = 'RGPD' LIMIT 1))
ON CONFLICT (id_livre, id_mot_cle) DO NOTHING;

INSERT INTO livre_auteurs (id_livre, id_auteur)
VALUES ((SELECT id_livre FROM livres WHERE isbn = '9782409037641'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BONNET' AND prenom_auteur = 'Nicolas' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037221'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LANGLET' AND prenom_auteur = 'Étienne' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'GRÉAU' AND prenom_auteur = 'Maxime' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019531'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LANGLET' AND prenom_auteur = 'Etienne' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022180'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'DUMINIL' AND prenom_auteur = 'Nicolas' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409035135'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'HUGON' AND prenom_auteur = 'Jérôme' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037368'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'GUÉRIN' AND prenom_auteur = 'Brice-Arnaud' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038068'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'GOUIGOUX' AND prenom_auteur = 'Jean-Philippe' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034145'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LADENT' AND prenom_auteur = 'Étienne' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037603'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'DEBRAUWER' AND prenom_auteur = 'Laurent' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'VAN ROBAEYS' AND prenom_auteur = 'Damien' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039645'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BEZET-TORRES' AND prenom_auteur = 'Jérôme' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'MOMMER' AND prenom_auteur = 'Christophe' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036132'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'GOUIGOUX' AND prenom_auteur = 'Jean-Philippe' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409019128'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'HIARD' AND prenom_auteur = 'Vincent' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033391'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BADREAU' AND prenom_auteur = 'Stéphane' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409036552'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LE MORVAN' AND prenom_auteur = 'Hervé' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038341'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BRILLANT' AND prenom_auteur = 'Alexandre' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037429'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'DAUSSIN' AND prenom_auteur = 'David' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038693'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'ANDRIANOELISON' AND prenom_auteur = 'Hajasolo' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409034121'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'VOLANT' AND prenom_auteur = 'Loïc' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038389'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'CABANTOUS' AND prenom_auteur = 'Pierre' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037764'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'PONS' AND prenom_auteur = 'Nicolas' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024504'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LARDIÈRE' AND prenom_auteur = 'Sébastien' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038327'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'NORIE' AND prenom_auteur = 'Eric' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031748'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'PERRÉ' AND prenom_auteur = 'Yannig' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409037726'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BARTOLONE' AND prenom_auteur = 'Thibault' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409020964'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'CHAZALLET' AND prenom_auteur = 'Sébastien' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409022722'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'SÉBASTIEN' AND prenom_auteur = 'Castiel' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409025679'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'Bonnet' AND prenom_auteur = 'Christophe' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409026553'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BISSON' AND prenom_auteur = 'Anne-Christine' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038006'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'RODRIGUEZ' AND prenom_auteur = 'Jean-Michel' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031953'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LE MASNE' AND prenom_auteur = 'Thibaut' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409012426'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'Israel' AND prenom_auteur = 'Marc' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031342'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'HAAS' AND prenom_auteur = 'Gérard' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031342'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'ASTIER' AND prenom_auteur = 'Stéphane' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409024986'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'POLINI' AND prenom_auteur = 'Eva' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409007934'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'Bourcy' AND prenom_auteur = 'Thierry' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409031380'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'Sébastien' AND prenom_auteur = 'Déon' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782746099715'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'Ebel' AND prenom_auteur = 'Franck' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038105'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'RASCAGNERES' AND prenom_auteur = 'Paul' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409038105'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LARINIER' AND prenom_auteur = 'Sébastien' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409039188'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'ASSOULINE' AND prenom_auteur = 'Jordan' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'ACISSI' AND prenom_auteur = 'Association' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BANCAL' AND prenom_auteur = 'Damien' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'EBEL' AND prenom_auteur = 'Franck' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'VICOGNE' AND prenom_auteur = 'Frédéric' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'FORTUNATO' AND prenom_auteur = 'Guillaume' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'BEIRNAERT-HUVELLE' AND prenom_auteur = 'Jacques' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'HENNECART' AND prenom_auteur = 'Jérôme' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'CLARHAUT' AND prenom_auteur = 'Joffrey' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'SCHALKWIJK' AND prenom_auteur = 'Laurent' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'RAULT' AND prenom_auteur = 'Raphaël' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'DUBOURGNOUX' AND prenom_auteur = 'Rémi' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'CROCFER' AND prenom_auteur = 'Robert' LIMIT 1)),
       ((SELECT id_livre FROM livres WHERE isbn = '9782409033667'),
        (SELECT id_auteur FROM auteurs WHERE nom_auteur = 'LASSON' AND prenom_auteur = 'Sébastien' LIMIT 1))
ON CONFLICT (id_livre, id_auteur) DO NOTHING;
